
=head1 SYNOPSIS

This little app is meant to be both a template for creating new wxperl 
applications (clone it to a new directory and immediately start adding code as 
needed) and a tutorial (clone it to a new directory and immediately start 
breaking things to learn how they work).

Either way, you'll want to have L<the wxWidgets 
documentation|http://docs.wxwidgets.org/stable/wx_contents.html> open while 
you're working.

=head1 APP LAYOUT

=head2 Assets

Media assets; images, sounds, etc.

L<MyApp::Model::Assets>

=head2 Dirs

Directories where your app stores various assets.

L<MyApp::Model::Dirs>

=head2 Database

The application stores its logs and any other data in an SQLite database that 
is not part of the original distribution.  Starting the app for the first time 
will create that database for you.

=head2 Fonts

Generalized font names.

L<MyApp::Model::Fonts>

=head2 Logging

L<MyApp::Model::DBILogger>

Loggers are available as a Bread::Board service to any part of the application 
with:

 my $logger = wxTheApp->logger;

Once you've got a logger, you can set the component (optional), which is 
simply a tag included with subsequent log entries to help identify which part 
of your program created the entries:

 $logger->component( "SubroutineBeingWorkedOnRightNow");

Log entries can now be created using any of several logging levels:

 $logger->info("Something just happened");
 $logger->warning("Something potentially bad just happened").

=head1 HELPERS

Pre-made elements that can be used as-is for their functionality (eg Log 
Viewer, Pod Viewer) or as examples ("How do I make my app make a sound?").

=head2 About

L<MyApp::GUI::Dialog::About>

=head2 Help

L<MyApp::GUI::Dialog::Help>

=head2 Log Viewer

L<MyApp::GUI::Dialog::LogViewer>

=head2 Main Frame

L<MyApp::GUI::MainFrame>

=head2 Menu Bar

L<MyApp::GUI::MainFrame::MenuBar>

=head2 Pod Viewer

L<MyApp::GUI::Dialog::PodViewer>

=head2 Splash Image

The splash image that displays upon application startup is purposely not part 
of the application.  The app may take several seconds to initialize, and we 
want the splash image to show up immediately.

So display of that image is handled in a C<BEGIN> block in the main 
C<bin/app.pl> program.

By default, the image being displayed is in C<var/img/splash.png>.  To display 
a different .png image, simply overwrite the existing C<splash.png> with your 
new image.


